version: '3'
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./data/registry:/var/lib/registry
      - ./registry.yaml:/etc/docker/registry/config.yml
  
  webhook:
    image: thecatlady/webhook
    ports:
      - "9000:9000"
    volumes:
      - ./hooks.yaml:/config/hooks.yml
      - ./webhook.fifo:/webhook.fifo
      - ./webhook.sh:/webhook.sh

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.crt:/etc/nginx/cert.crt
      - ./cert.key:/etc/nginx/cert.key
      - ./auth.htpasswd:/etc/nginx/auth.htpasswd
      - xaufome:/var/www/xaufome
    depends_on:
      # - website
      - xaufome
      - atrellado
      - commits

  # Subdomains

  website:
    image: localhost:5000/website:latest
    expose:
      - "80:80"

  xaufome:
    image: localhost:5000/xaufome:latest
    volumes:
      - xaufome:/var/www/html
      # - ./data/xaufome.db:/var/www/html/database/main.db
    expose:
      - "9000:9000"

  atrellado:
    image: localhost:5000/atrellado:latest
    env_file:
      - ./atrellado.env
    expose:
      - "80:80"
    depends_on:
      - postgres
      - smtp

  commits:
    image: localhost:5000/commits:latest
    env_file:
      - ./commits.env
    expose:
      - "80:80"
    depends_on:
      - mongo

  # Other services

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./postgres.env
    expose:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    restart: always
    expose:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  smtp:
    image: namshi/smtp:latest
    restart: always
    expose:
      - "25:25"

volumes:
  xaufome:
