x-base-service: &base-service
  restart: unless-stopped
  labels:
    com.centurylink.watchtower.scope: hosting
  logging:
    driver: loki
    options:
      loki-url: http://10.69.0.2:3100/loki/api/v1/push
      loki-retries: 2
      loki-max-backoff: 800ms
      loki-timeout: 1s
      keep-file: 'true'
  depends_on:
    - loki

services:
  registry:
    <<: *base-service
    image: registry:3
    environment:
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: inmemory
    expose:
      - "5000:5000"
    volumes:
      - ./data/registry:/var/lib/registry
    networks:
      default:
      internal:
        ipv4_address: 10.69.0.3

  watchtower:
    <<: *base-service
    image: containrrr/watchtower:latest
    environment:
      WATCHTOWER_SCOPE: "hosting"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  caddy:
    <<: *base-service
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "2019:2019"
    volumes:
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config
      - ./secrets/registry-auth:/etc/caddy/registry-auth:ro
      - website:/var/www/website:ro
      - latex-previewer:/var/www/latex-previewer:ro
      - schema:/var/www/schema:ro
      - xaufome:/var/www/xaufome:ro
      - commits:/var/www/commits:ro
      - sgi:/var/www/sgi:ro
    configs:
      - source: caddy
        target: /etc/caddy/Caddyfile

  # Subdomains

  website:
    <<: *base-service
    image: 10.69.0.3:5000/website
    volumes:
      - website:/app:rw

  latex-previewer:
    <<: *base-service
    image: 10.69.0.3:5000/latex-previewer
    volumes:
      - latex-previewer:/app:rw

  schema:
    <<: *base-service
    image: 10.69.0.3:5000/schema
    volumes:
      - schema:/app:rw

  xaufome:
    <<: *base-service
    image: 10.69.0.3:5000/xaufome
    volumes:
      - xaufome:/var/www/html
      - ./data/xaufome.db:/var/www/html/database/main.db
    expose:
      - "9000:9000"

  atrellado:
    <<: *base-service
    image: 10.69.0.3:5000/atrellado
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: atrellado
      DB_USERNAME: atrellado

      MAIL_MAILER: smtp
      MAIL_HOST: smtp
      MAIL_PORT: 25
    env_file:
      - ./secrets/atrellado.env
    expose:
      - "80:80"
    depends_on:
      - postgres
      - smtp
      - loki

  commits:
    <<: *base-service
    image: 10.69.0.3:5000/commits
    volumes:
      - commits:/app:rw

  luis:
    <<: *base-service
    image: 10.69.0.3:5000/luis
    environment:
      SOLR_URL: http://solr:8983/solr
      SOLR_CORE: luis
    depends_on:
      - solr

  sdle:
    <<: *base-service
    image: 10.69.0.3:5000/sdle
    expose:
      - "3000:3000"
  
  sdle-server:
    <<: *base-service
    image: 10.69.0.3:5000/sdle-server
    environment:
      CLUSTER_STORAGE_DRIVER_TYPE: file_system
    volumes:
      - ./data/sdle-server:/app/data:rw
    expose:
      - "8080:8080"

  sgi:
    <<: *base-service
    image: 10.69.0.3:5000/sgi
    volumes:
      - sgi:/app:rw

  jmm:
    <<: *base-service
    image: 10.69.0.3:5000/jmm
    expose:
      - "3000:3000"

  # Admin stuff

  authentik-server:
    <<: *base-service
    image: ghcr.io/goauthentik/server:latest
    command: server
    env_file:
      - ./secrets/authentik.env
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
    expose:
      - "9000:9000"
      - "9300:9300"
      - "9443:9443"
    volumes:
      - ./data/authentik/media:/media
      - ./data/authentik/templates:/templates
    depends_on:
      - postgres
      - redis
      - loki

  authentik-worker:
    <<: *base-service
    image: ghcr.io/goauthentik/server:latest
    command: worker
    env_file:
      - ./secrets/authentik.env
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
    volumes:
      - ./data/authentik/media:/media
      - ./data/authentik/templates:/templates
      - ./data/authentik/certs:/certs
    depends_on:
      - postgres
      - redis
      - loki

  authentik-ldap:
    <<: *base-service
    image: ghcr.io/goauthentik/ldap:latest
    env_file:
      - ./secrets/authentik-ldap.env
    environment:
      AUTHENTIK_HOST: https://authentik-server:9443
      AUTHENTIK_INSECURE: "true"
    expose:
      - "3389:3389"
      - "6636:6636"
      - "9300:9300"
  
  pgadmin:
    <<: *base-service
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ./secrets/pgadmin.env
    environment:
      PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "['oauth2']"
      PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USERS: "True"
      PGADMIN_CONFIG_OAUTH2_CONFIG: |
        [{
          'OAUTH2_NAME': 'authentik',
          'OAUTH2_DISPLAY_NAME' : 'Authentik',
          'OAUTH2_CLIENT_ID' : __import__('os').environ['AUTHENTIK_CLIENT_ID'],
          'OAUTH2_CLIENT_SECRET' : __import__('os').environ['AUTHENTIK_CLIENT_SECRET'],
          'OAUTH2_TOKEN_URL' : 'https://sso.toino.pt/application/o/token/',
          'OAUTH2_AUTHORIZATION_URL' : 'https://sso.toino.pt/application/o/authorize/',
          'OAUTH2_API_BASE_URL' : 'https://sso.toino.pt/',
          'OAUTH2_USERINFO_ENDPOINT' : 'https://sso.toino.pt/application/o/userinfo/',
          'OAUTH2_SERVER_METADATA_URL' : 'https://sso.toino.pt/application/o/pgadmin/.well-known/openid-configuration',
          'OAUTH2_SCOPE' : 'openid email profile',
          'OAUTH2_BUTTON_COLOR' : '#FD4B2D',
          'OAUTH2_ICON' : 'fa fa-lock',
        }]
    expose:
      - "80:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
      - loki

  prometheus:
    <<: *base-service
    image: prom/prometheus:latest
    restart: unless-stopped
    expose:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/prometheus
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
  
  loki:
    <<: *base-service
    image: grafana/loki:latest
    restart: unless-stopped
    expose:
      - "3100:3100"
    volumes:
      - ./data/loki:/loki
    configs:
      - source: loki
        target: ./config.yaml
    networks:
      default:
      internal:
        ipv4_address: 10.69.0.2
    depends_on: []

  promtail:
    <<: *base-service
    image: grafana/promtail:latest
    command: -config.file=config.yaml
    restart: unless-stopped
    volumes:
      - ./logs:/logs:ro
    configs:
      - source: promtail
        target: ./config.yaml
  
  grafana:
    <<: *base-service
    image: grafana/grafana:latest
    restart: unless-stopped
    expose:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: "https://grafana.toino.pt/"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Authentik"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://sso.toino.pt/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://sso.toino.pt/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://sso.toino.pt/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://sso.toino.pt/application/o/grafana/end-session/"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'Superusers') && ('Admin' || 'Editor') || 'Viewer'"
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
    env_file:
      - ./secrets/grafana.env
    volumes:
      - ./data/grafana:/var/lib/grafana
  
  cadvisor:
    <<: *base-service
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    expose:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
  
  node-exporter:
    <<: *base-service
    image: prom/node-exporter:latest
    restart: unless-stopped
    pid: host
    command:
      - --path.rootfs=/host
    expose:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave

  # Other services

  postgres:
    <<: *base-service
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./secrets/postgres.env
    environment:
      - POSTGRES_MULTIPLE_DATABASES=atrellado,authentik
    expose:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    configs:
      - source: postgres
        target: /docker-entrypoint-initdb.d/init-postgres.sh

  redis:
    <<: *base-service
    image: redis:7-alpine
    restart: unless-stopped
    expose:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  smtp:
    <<: *base-service
    image: namshi/smtp:latest
    restart: unless-stopped
    expose:
      - "25:25"

  solr:
    <<: *base-service
    image: 10.69.0.3:5000/solr
    restart: unless-stopped
    expose:
      - "8983:8983"

volumes:
  website:
  latex-previewer:
  schema:
  xaufome:
  commits:
  sgi:

configs:
  loki:
    file: ./config/loki.yaml
  caddy:
    file: ./config/Caddyfile
  postgres:
    file: ./config/init-postgres.sh
  prometheus:
    file: ./config/prometheus.yml
  promtail:
    file: ./config/promtail.yaml

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.69.0.0/16
          gateway: 10.69.0.1
