global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'authentik'
    static_configs:
      - targets: ['authentik-server:9300']
  - job_name: 'authentik-ldap'
    static_configs:
      - targets: ['authentik-ldap:9300']
  - job_name: 'solr'
    static_configs:
      - targets: ['solr:8983']
        metrics_path: '/solr/admin/metrics'
